### ISSUE TITLE
[BUG] PRT not working without sender overlay active

### ISSUE THREAD

**Issue by nieber** [PhenomDevel/PhenomRaidTools#26]
yesterday we were reclearing mythic CN but PRT stopped sending messages to others on Sire denathrius (worked on SLG). So I opened the sender overlay to check if the triggers broke, but it then started working again. I thought it was fixed so I closed the overlay and it stopped working again. I couldn't verify if it started again when I reopened it cause we killed it on the pull where I closed the overlay.

the export I was using:
[export.txt](https://github.com/PhenomDevel/PhenomRaidTools/files/6142737/export.txt)
 
After the raid one of the raiders told me that some triggers were still working in those first pulls, the only trigger I'm sure wasn't working when the overlay was closed was the P1 timer.

**Comment by PhenomDevel** [comment]
Which version of the addon did you use?

**Comment by nieber** [comment]
2.3.10

**Comment by PhenomDevel** [comment]
Ok thanks.

I think i found the bug. All repeating checks were only processed when the sender overlay was activated. So i think you're right with the guess that the timers did not work. This only affects timers as far as i can see maybe that's why you got the reports that some messages came through (rotations and such).

I'll push an update once i fixed it.

**Comment by PhenomDevel** [comment]
2.3.12 should fix this issue. If it doesn't please reopen the ticket. I will close it for now.
