### ISSUE TITLE
[Feature Request] Add functionality to have multiple Boss Templates for the same Encounter with only one active at the same time

### ISSUE THREAD

**Issue by Hayato2846** [PhenomDevel/PhenomRaidTools#29]
I really love the template system, how it works and how different boss templates can be shared via Discord. But if I want to try another template or just want to look how others added common boss rotations or triggers I have to delete or merge my boss template with the other template. I get the idea behind it because you want to disable the ability to have multiple boss templates active at the same time to reduce spammable messages but I think it'd be helpful to just check that only one template for a given encounter id is active at the same time. With that check changed you can import / manage multiple templates for a given encounter id, check things, copy things between templates with the same anti-spam protection in mind as in your current version.

**Comment by PhenomDevel** [comment]
My main concern is not the part that you could have multiple encounters for the same id. The problem i see is that if you really have more than one encounter for the same id you need an easy to use and understand way to select the encounter you actually want to execute for the given id.

I don't see an easy way of doing so because the encounters are strongly separated in the data. It would have to be something like a checkbox to say "this is the active encounter for id XY" which would lead to changing some other encounters behind the scenes.

Also a big problem with that is in the current data there is a binding between id and encounter table. So to be able to have multiple encounters for the same id i'd have to bind the id to a table of tables and that has big impact on the whole structure.

**Comment by Hayato2846** [comment]
Couldnt you just handle that with the already existing enabled flag?

I get the point regarding id <=> table of encounters. There need to be some part of migrating the old structure to new.

But the identifier at this point beside encounter id is the template name. Two templates, same encounter id, identified in the list by their names (which are separate...or at least an "(2)" etc. at the end). Color Highlighting for enabled / disabled encounters already exist and when you try to enable the 2nd encounter there's a warning like "Template with name 'XYZ' is already enabled for given encounter. Would you like to enable Template "XYZ (2)" and disable Template 'XYZ'?".

But yeah even with that in mind it's a bigger change just because of a changed data / table structure. Importing older templates would be a challenge too for that.

**Comment by PhenomDevel** [comment]
This was added in version 2.5.0-BETA and will be ready in the next release.

**Comment by PhenomDevel** [comment]
Publicly available since 2.6.0
